version: '3.9'


services:

  web_manager:
    build: ./web_manager/
    environment:
      - WEB_MANAGER_REPO__SQLALCHEMY_DATABASE=znoOData
      - WEB_MANAGER_REPO__SQLALCHEMY_DRIVERNAME=postgresql+psycopg2
      - WEB_MANAGER_REPO__SQLALCHEMY_HOST=database
      - WEB_MANAGER_REPO__SQLALCHEMY_PASSWORD=do-not-expell-please
      - WEB_MANAGER_REPO__SQLALCHEMY_PORT=5432
      - WEB_MANAGER_REPO__SQLALCHEMY_USERNAME=Rutovol82
      - WEB_MANAGER_SECRET_KEY=incredibly-secret-key
    command: [ "python", "-m", "web_manager"]
    networks:
      - service_ntw
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - web_manager

  # Service, runs V1.1 (#lab-1 #primary) schema database initialization
  # (will not have an effect if tables already exist)
  maintenance__v1.1__init-db:
    build: ./db_utils/
    secrets:
      - db-password
    command: [ "python", "-m", "db_utils",
               "-h", "database", "-p", "5432",
               "-d", "znoOData", "-U", "Rutovol82",
               "-P", "@/run/secrets/db-password",
               "-lL", "INFO",
               "V1.1__init" ]
    networks:
      - service_ntw
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - V1.1__init-db

  # Service, runs test ZNO OData injection
  # into the V1.1 (#lab-1 #primary) schema database
  maintenance__v1.1__inject__test-data:
    build: ./db_utils/
    secrets:
      - db-password
    volumes:
      - ./.work/.zno-odata-files-test:/.work/.zno-odata-files-test:read_only
      - zno-odata-injection-cache:/.work/zno-odata-injection-cache
      - ./.work/zno-odata-injections:/.work/zno-odata-injections
    command: [ "python", "-m", "db_utils",
               "-h", "database", "-p", "5432",
               "-d", "znoOData", "-U", "Rutovol82",
               "-P", "@/run/secrets/db-password",
               "-lL", "INFO",
               "-fT", "zno-odata-injections/inject-reduced-2019-k100.timing.csv",
               "V1.1__inject",
               "zno-odata-injections/inject-reduced-2019-k100.yaml",
               "-M", "CACHE_DISABLE" ]
    networks:
      - service_ntw
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - V1.1__inject__test-data

  # Service, runs work ZNO OData injection for years 2020-2021
  # into the V1.1 (#lab-1 #primary) schema database
  # (data files will be downloaded if not exists)
  maintenance__v1.1__inject__work-data:
    build: ./db_utils/
    secrets:
      - db-password
    volumes:
      - zno-odata-files:/.work/.zno-odata-files
      - zno-odata-injection-cache:/.work/zno-odata-injection-cache
      - ./.work/zno-odata-injections:/.work/zno-odata-injections
      - ./.work/.scripts:/.work/.scripts:read_only
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        .scripts/download.sh -Fd .zno-odata-files -Bf -y 2020 -y 2021
        python -m db_utils -h database -p 5432                                      \
                           -d znoOData -U Rutovol82                                 \
                           -P @/run/secrets/db-password                             \
                           -lL INFO                                                 \
                           -fT zno-odata-injections/inject-2020-2021.timing.csv     \
                           V1.1__inject                                             \
                           zno-odata-injections/inject-2020-2021.yaml               \
                           -M CACHE_DISABLE
    networks:
      - service_ntw
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - V1.1__inject__work-data

  # Service, runs test ZNO OData injection
  # into the V2.1 (#lab-2 #primary) schema database
  maintenance__v2.1__inject__test-data:
    build: ./db_utils/
    secrets:
      - db-password
    volumes:
      - ./.work/.zno-odata-files-test:/.work/.zno-odata-files-test:read_only
      - zno-odata-injection-cache:/.work/zno-odata-injection-cache
      - ./.work/zno-odata-injections:/.work/zno-odata-injections
    command: [ "python", "-m", "db_utils",
               "-h", "database", "-p", "5432",
               "-d", "znoOData", "-U", "Rutovol82",
               "-P", "@/run/secrets/db-password",
               "-lL", "INFO",
               "-fT", "zno-odata-injections/inject-reduced-2019-k100.timing.csv",
               "V2.1__inject",
               "zno-odata-injections/inject-reduced-2019-k100.yaml",
               "-M", "CACHE_DISABLE" ]
    networks:
      - service_ntw
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - V2.1__inject__test-data

  # Service, runs work ZNO OData injection for years 2020-2021
  # into the V2.1 (#lab-2 #primary) schema database
  # (data files will be downloaded if not exists)
  maintenance__v2.1__inject__work-data:
    build: ./db_utils/
    secrets:
      - db-password
    volumes:
      - zno-odata-files:/.work/.zno-odata-files
      - zno-odata-injection-cache:/.work/zno-odata-injection-cache
      - ./.work/zno-odata-injections:/.work/zno-odata-injections
      - ./.work/.scripts:/.work/.scripts:read_only
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        .scripts/download.sh -Fd .zno-odata-files -Bf -y 2020 -y 2021
        python -m db_utils -h database -p 5432                                      \
                           -d znoOData -U Rutovol82                                 \
                           -P @/run/secrets/db-password                             \
                           -lL INFO                                                 \
                           -fT zno-odata-injections/inject-2020-2021.timing.csv     \
                           V2.1__inject                                             \
                           zno-odata-injections/inject-2020-2021.yaml               \
                           -M CACHE_DISABLE
    networks:
      - service_ntw
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - V2.1__inject__work-data

  # Service, runs flyway migration from
  # not-versioned empty schema to V1.1 (#lab-1 #primary)
  flyway__migrate__ne-v1.1:
    image: flyway/flyway
    secrets:
      - db-password
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./flyway/sql:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://database:5432/znoOData
      - FLYWAY_USER=Rutovol82
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        flyway -configFiles="/flyway/conf/migration__nE-V1.1__flyway.conf"      \
               -password="$$(cat "/run/secrets/db-password")"                   \
               migrate
    networks:
      - service_ntw
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - migrate__nE-V1.1

  # Service, runs flyway migration from
  # not-versioned empty schema to V2.1 (#lab-2 #primary)
  flyway__migrate__ne-v2.1:
    image: flyway/flyway
    secrets:
      - db-password
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./flyway/sql:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://database:5432/znoOData
      - FLYWAY_USER=Rutovol82
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        flyway -configFiles="/flyway/conf/migration__nE-V2.1__flyway.conf"      \
               -password="$$(cat "/run/secrets/db-password")"                   \
               migrate
    networks:
      - service_ntw
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - migrate__nE-V2.1

  # Service, runs flyway baseline on version V1.1
  # and migration to V2.1 (#lab-2 #primary)
  flyway__migrate__nv1.1-v2.1:
    image: flyway/flyway
    secrets:
      - db-password
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./flyway/sql:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://database:5432/znoOData
      - FLYWAY_USER=Rutovol82
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        flyway -configFiles="/flyway/conf/migration__nV1.1-V2.1__flyway.conf"     \
               -password="$$(cat "/run/secrets/db-password")"                     \
               migrate
    networks:
      - service_ntw
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - migrate__nV1.1-V2.1

  # Database service
  database:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=znoOData
      - POSTGRES_USER=Rutovol82
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - service_ntw
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "znoOData", "-U", "Rutovol82" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db-data:
  zno-odata-files:
  zno-odata-injection-cache:


secrets:
  db-password:
    file: .secrets/db-password


networks:
  service_ntw:
